### ISSUE TITLE
BUG: Runaway CPU - Fixed in Newer Code

### ISSUE THREAD

**Issue by localsite** [USEPA/useeio-widgets#60] opened 2021-05-11 21:50 UTC
The browser sometimes freezes. This effects all the other browser window. I had to do a force quit after waiting 15 minutes. I'm using the Brave browser.
 
The runaway CPU occurs when choosing "Unselect All" and probably also "Choose All" on the input-output chart. First occurred May 10.

**Comment by TheTisiboth** [comment] 2021-05-27 09:13
I observed it also a few times. However, I am not able to reproduce the bug anymore. I may have fix it without knowing. Let me know if it still happens ( I will also be aware of it from now).

**Comment by modelearth** [comment] 2021-06-09 23:14
Yes, it's fixed in you newer code. (I pulled that down today after falling asleep after lunch waiting for the runaway processor.)  I added a warning note on the [widget overview page](https://model.earth/io/charts/).  Let's leave this issue active so others are aware that the following build solves the problem: https://thetisiboth.github.io/useeio-widget-builds/

**Comment by TheTisiboth** [comment] 2021-06-10 07:11
Ok, great news!

**Closed** 2021-06-16 16:29 UTC
Labels: bug, currrent
